import Head from 'next/head'
import Box from "../components/Box";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tailwind Grid Layout in Next JS</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='app'>
        <header className='bg-gray-200'>
          <div className='container h-16'></div>
        </header>

        <main>
          <section>
            <div className='container'>
              <div className='grid grid-cols-1 md:grid-cols-6'>
                <div className='grid-col md:col-start-2 md:col-span-4'>
                  <Box/>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className='container'>
              <div className="grid md:grid-cols-2">
                <div className='grid-col'>
                  <Box content="COLUMN 1"/>
                </div>
                <div className='grid-col'>
                  <Box content="COLUMN 2"/>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className='container'>
              <div className="grid grid-cols-1 md:grid-cols-4">
                <div className='grid-col md:col-span-3'>
                  <Box content="COLUMN 1"/>
                </div>
                <div className='grid-col'>
                  <Box content="COLUMN 2"/>
                </div>
              </div>
            </div>
          </section>

          <section>
            <div className='container'>
              <div className="grid grid-cols-1 md:grid-cols-4">
                <div className='grid-col'>
                  <Box content="COLUMN 1"/>
                </div>
                <div className='grid-col md:col-span-2'>
                  <Box content="COLUMN 2"/>
                </div>
                <div className='grid-col'>
                  <Box content="COLUMN 3"/>
                </div>
              </div>
            </div>
          </section>
        </main>

        <footer className='bg-gray-200'>
          <div className='container'>
            <div className='w-full h-60' />
          </div>
        </footer>
      </div>
    </div>
  )
}
